// Accurate
export const MILLISECONDS_IN_A_SECOND = 1000;
export const MILLISECONDS_IN_A_MINUTE = MILLISECONDS_IN_A_SECOND * 60;
export const MILLISECONDS_IN_AN_HOUR = MILLISECONDS_IN_A_MINUTE * 60;
export const MILLISECONDS_IN_A_DAY = MILLISECONDS_IN_AN_HOUR * 24;
export const MILLISECONDS_IN_A_WEEK = MILLISECONDS_IN_A_DAY * 7;

// Inaccurate
export const DAYS_IN_A_YEAR = 365;
export const MILLISECONDS_IN_A_YEAR = MILLISECONDS_IN_A_DAY * DAYS_IN_A_YEAR;
export const MILLISECONDS_IN_A_MONTH = MILLISECONDS_IN_A_YEAR / 12;
